# Módulo 3

In [2]:
# Apuntes Módulo 3

import numpy as np

#crear Arrays a partir de una lista

vector = np.array([1,2,3,4,5,6,7,8,9])
vector


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
type (vector)

numpy.ndarray

In [3]:
#A partir de una tupla ( es inmutable)
vector = np.array(("a", "b", "c"))
vector

array(['a', 'b', 'c'], dtype='<U1')

In [4]:
# a partir de un conjunto 

vector = np.array ({1,2,3,4,5,3,6,4,5})
vector

array({1, 2, 3, 4, 5, 6}, dtype=object)

In [8]:
#funcion arange 

vector = np.arange (3,10,2) #Del 3-10,con salto de 2 *No llega al 10! mirar manual 
vector

array([3, 5, 7, 9])

In [11]:
#Rellando con '0', '1'

vector = np.ones(4)
vector



array([1., 1., 1., 1.])

In [10]:
vector = np.zeros(3)
vector

array([0., 0., 0.])

In [12]:
# Funcion linspace 

vector = np.linspace(1,10,5) #Genera valores entre 1,10 con separacion de 5

vector

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
#Valores de tipos distintos
vector = np.array([1,2,3,4,5])
vector


array([1, 2, 3, 4, 5])

In [14]:
type(vector[0])

numpy.int64

In [16]:
vector = np.array([1,2,3.0,5,6]) # pasa todo a punto float, solo debe haber una variable si hay 2 tipos automaticamente pasa a ser del tipo2 

vector

array([1., 2., 3., 5., 6.])

In [18]:
vector = np.array([1,2,3,4, False]) 
vector

# Los booleanos contemplan false 0, true 1 - se engloba a los enteros. 

array([1, 2, 3, 4, 0])

In [3]:
vector = np.array([1,2,3,"hola", True])
vector


array(['1', '2', '3', 'hola', 'True'], dtype='<U21')

In [4]:
# COPIAR ARRAYS 
vector1 = np.array([1,2,3,4])
vector1

array([1, 2, 3, 4])

In [5]:
vector2 = vector1
vector2

array([1, 2, 3, 4])

In [6]:
id(vector1)

140331400645104

In [7]:
id(vector2)

140331400645104

In [8]:
vector3 = np.copy(vector1)
vector3

array([1, 2, 3, 4])

In [9]:
id(vector3)

140331378467792

In [10]:
vector1[0] = 14
vector1

array([14,  2,  3,  4])

In [11]:
vector2

array([14,  2,  3,  4])

In [13]:
vector3[0]

1

APUNTES 31/10/23 - MATRICES (ARRAY MULTIDIMENSIONALES)


In [14]:
lista =[1,2,3,4]
vector = np.array([1,2,3,4])
vector

array([1, 2, 3, 4])

In [18]:
lista_de_listas=[[1,2,3],[4,5,6]]
matriz =np.array(lista_de_listas)
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
vector[2]

3

In [21]:
matriz[1,1]
matriz[1][1]

5

In [32]:
matriz3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])
matriz3d

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [33]:
matriz3d[0,1,0]

3

In [35]:
vector.ndim


1

In [36]:
matriz.ndim

2

In [37]:
matriz =np.zeros([5,3],dtype="int32")
matriz

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

PROPIEDADES DE MATRICES

In [40]:
print(vector.size)
print(vector.shape)
print(vector.ndim)

4
(4,)
1


In [42]:
print(matriz.size)
print(matriz.shape)
print(matriz.ndim)

15
15
(5, 3)
2


REDIMENSIONAR

In [46]:
vector = np.array([6,5,4,3,2,1,])
vector

array([6, 5, 4, 3, 2, 1])

In [47]:
matriz = vector.reshape(3,2)
matriz

array([[6, 5],
       [4, 3],
       [2, 1]])

In [51]:
matriz2 = matriz.reshape(3,2)
matriz2


array([[6, 5],
       [4, 3],
       [2, 1]])

In [52]:
matriz2.reshape(6,1)

array([[6],
       [5],
       [4],
       [3],
       [2],
       [1]])

In [54]:
matriz2.reshape(1,6)[0]

array([6, 5, 4, 3, 2, 1])

AÑADIR Y BORRAR ELEMENTOS

In [56]:
vector = np.array(["blanco","azul","rojo"])
vector

array(['blanco', 'azul', 'rojo'], dtype='<U6')

In [59]:
vector2 = np.append(vector,["verde"]) # añade datos al vector
vector2

array(['blanco', 'azul', 'rojo', 'verde'], dtype='<U6')

In [72]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
matriz_2 = np.append(matriz,[[7,8,9]],axis =0)
matriz_2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
matriz3 = np.append(matriz,[[7],[8]], axis = 1)
matriz3

array([[1, 2, 4, 7],
       [4, 5, 6, 8]])

In [70]:
np.delete(matriz,1,axis =0)

array([[1, 2, 4]])

In [71]:
np.delete(matriz,1,axis=1)

array([[1, 4],
       [4, 6]])

OPERACIONES CON ARRAYS Y MATRICES


In [74]:
matriz = np.random.rand(2,3)
matriz 

array([[0.62335658, 0.97177663, 0.73023443],
       [0.36924712, 0.16259876, 0.83852862]])

Matriz de numeros aleatorios con distribucion media, estándar 1

In [76]:
matriz = np.random.randn(2,3)
matriz

array([[ 1.08535699, -0.49726839, -1.86338847],
       [ 0.42660497, -0.23307454, -0.18802338]])

In [77]:
np.median(matriz)

-0.21054895630313347

In [79]:
matriz = np.array([[1,2,3],[4,5,6]])
np.mean(matriz)

3.5

In [80]:
np.mean(matriz,axis=0)

array([2.5, 3.5, 4.5])

In [81]:
np.mean(matriz,axis=1)

array([2., 5.])

In [83]:
matriz1 = np.array([[1,2,3],[4,5,6]])
matriz2 = np.array([[3,2,1],[6,5,4]])

In [84]:
matriz1 + matriz2

array([[ 4,  4,  4],
       [10, 10, 10]])

In [90]:
matriz1 - matriz2

array([[0, 0, 0],
       [0, 0, 0]])

In [88]:
matriz1*3

array([[ 9,  6,  3],
       [18, 15, 12]])

In [89]:
matriz1 > 1

array([[ True,  True, False],
       [ True,  True,  True]])

In [92]:
matriz.sum(axis =0)

array([5, 7, 9])

In [93]:
matriz1.min()

1

In [94]:
matriz1.max()

6

In [97]:
matriz1.transpose()

array([[3, 6],
       [2, 5],
       [1, 4]])

ACCESO A PARTES DE UNA MATRIZ

In [99]:
vector = np.array([1,2,3,4,5,6])
vector[3]

4

In [100]:
vector[-1]

6

In [101]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
matriz[-1]

array([4, 5, 6])

In [103]:
matriz[1:]

array([[4, 5, 6]])